Repository Trively/Trively-server, pull requests merged in 2024-04, with the labels that each got.

#3 [style] 프로젝트 골격 설정 (#2)
  pom.xml
  src/main/java/com/jida/EnjoyTripApplication.java
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/dto/BaseResponse.java
  src/main/java/com/jida/dto/req/MemberRequestDto.java
  src/main/java/com/jida/dto/res/member/MemberResponseDto.java
Labels: JIHUN

#5 [FEAT] 게시판 카테고리 조회 기능 추가
  src/main/java/com/jida/EnjoyTripApplication.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/BoardController.java
  src/main/java/com/jida/dto/res/board/BoardListResponse.java
  src/main/java/com/jida/dto/res/board/BoardListResponseDto.java
  src/main/java/com/jida/mapper/BoardMapper.java
  src/main/java/com/jida/service/BoardService.java
  src/main/java/com/jida/service/BoardServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/board.xml
Labels: JIHUN, FEAT

#8 [FEAT] 게시글 저장, 상세조회 API
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/BoardController.java
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/domain/Post.java
  src/main/java/com/jida/dto/req/PostSaveRequestDto.java
  src/main/java/com/jida/dto/res/post/PostDetailResponse.java
  src/main/java/com/jida/dto/res/post/PostDetailResponseDto.java
  src/main/java/com/jida/mapper/BoardMapper.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/board.xml
  src/main/resources/mapper/post.xml
Labels: JIHUN, FEAT

#11 [FEAT] 게시글 수정 API
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FEAT

#12 [FEAT] 여행지 목록 조회 API
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/AttractionController.java
  src/main/java/com/jida/domain/Attraction.java
  src/main/java/com/jida/dto/res/attraction/AttractionListResponse.java
  src/main/java/com/jida/dto/res/attraction/AttractionListResponseDto.java
  src/main/java/com/jida/mapper/AttractionMapper.java
  src/main/java/com/jida/service/AttractionService.java
  src/main/java/com/jida/service/AttractionServiceImpl.java
  src/main/resources/mapper/attraction.xml
Labels: DAIN, FEAT, FIX

#14 [FEAT] 게시글 삭제 API
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/dto/res/post/PostResponse.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: DAIN, FEAT

#16 [FEAT] 게시글 전체 조회 API
  src/main/java/com/jida/common/PageInfo.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/dto/res/post/PostListResponse.java
  src/main/java/com/jida/dto/res/post/PostListResponseDto.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FEAT

#18 [FEAT] 게시글 상세조회 시 조회수 상승 로직 추가
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FEAT
