Repository Trively/Trively-server, pull requests merged in 2024-05, with the labels that each got.

#20 [FIX] 게시글 전체 조회 API 수정
  src/main/java/com/jida/domain/Post.java
  src/main/java/com/jida/dto/res/post/PostListResponseDto.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FIX

#22 [FIX] 게시판 카테고리 API 수정
  src/main/java/com/jida/dto/res/board/BoardListResponseDto.java
Labels: JIHUN, FIX

#24 [FIX] 게시글 전체조회 쿼리문 수정
  src/main/resources/mapper/post.xml
Labels: JIHUN, FIX

#26 [FIX] http 메서드 수정 (#25)
  src/main/java/com/jida/controller/MemberController.java
Labels: DAIN, FIX

#28 [FEAT] 스프링 시큐리티 CORS 에러 처리 추가
  pom.xml
  src/main/java/com/jida/EnjoyTripApplication.java
  src/main/java/com/jida/security/SecurityConfig.java
Labels: JIHUN, FEAT

#30 [FIX] jwt 구현 전, security 인증 범위 변경
  src/main/java/com/jida/security/SecurityConfig.java
Labels: JIHUN, FIX

#33 [REFACTOR] 게시글 도메인 필드 수정
  src/main/java/com/jida/domain/Post.java
  src/main/java/com/jida/dto/res/post/PostListResponseDto.java
  src/main/java/com/jida/mapper/BoardMapper.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/board.xml
  src/main/resources/mapper/post.xml
Labels: JIHUN, FIX

#34 [REFACTOR] 도메인 setter 삭제
  src/main/java/com/jida/domain/Attraction.java
  src/main/java/com/jida/domain/Board.java
  src/main/java/com/jida/domain/Member.java
  src/main/java/com/jida/domain/Post.java
  src/main/java/com/jida/service/PostServiceImpl.java
Labels: JIHUN, FIX

#36 [FEAT] 게시글 상세 조회 API 사용자 이름 추가
  src/main/java/com/jida/dto/res/post/PostDetailResponseDto.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FEAT

#38 [FEAT] 게시글 좋아요 API 구현
  .DS_Store
  src/.DS_Store
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/domain/PostLike.java
  src/main/java/com/jida/mapper/PostLikeMapper.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/security/SecurityConfig.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/postLike.xml
Labels: JIHUN, FEAT

#40 [FEAT] 나의 스크랩 전체 조회 및 생성 API
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/domain/PostScrap.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/mapper/PostScrapMapper.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
  src/main/resources/mapper/postScrap.xml
Labels: JIHUN, FEAT

#43 [FEAT] 댓글 및 대댓글 생성 API 구현
  pom.xml
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/CommentController.java
  src/main/java/com/jida/domain/Comment.java
  src/main/java/com/jida/dto/req/CommentSaveRequestDto.java
  src/main/java/com/jida/dto/res/comment/CommentDetailResponse.java
  src/main/java/com/jida/dto/res/comment/CommentDetailResponseDto.java
  src/main/java/com/jida/dto/res/comment/CommentResponse.java
  src/main/java/com/jida/exception/CustomException.java
  src/main/java/com/jida/exception/RestExceptionHandler.java
  src/main/java/com/jida/mapper/CommentMapper.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/CommentService.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/comment.xml
Labels: JIHUN, FEAT

#45 [FEAT] 댓글, 대댓글 조회 API 구현
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/CommentController.java
  src/main/java/com/jida/dto/res/comment/CommentDetailResponseDto.java
  src/main/java/com/jida/dto/res/comment/CommentListResponse.java
  src/main/java/com/jida/dto/res/comment/CommentListResponseDto.java
  src/main/java/com/jida/mapper/CommentMapper.java
  src/main/java/com/jida/service/CommentService.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/resources/mapper/comment.xml
Labels: JIHUN, FEAT

#47 [FEAT] 댓글 삭제 API 구현
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/CommentController.java
  src/main/java/com/jida/mapper/CommentMapper.java
  src/main/java/com/jida/service/CommentService.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/resources/mapper/comment.xml
Labels: JIHUN, FEAT

#49 [FIX] 대댓글의 대댓글 작성 API 로직 수정
  src/main/java/com/jida/service/CommentServiceImpl.java
Labels: JIHUN, FIX

#51 [FEAT] 댓글 작성 및 삭제 시 갯수 최신화
  src/main/java/com/jida/domain/Post.java
  src/main/java/com/jida/dto/res/post/PostDetailResponseDto.java
  src/main/java/com/jida/dto/res/post/PostListResponseDto.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FEAT

#53 [FEAT] 좋아요 시 갯수 최신화 및 게시글 조회 시 좋아요 갯수 반환
  src/main/java/com/jida/domain/Post.java
  src/main/java/com/jida/dto/res/post/PostDetailResponseDto.java
  src/main/java/com/jida/dto/res/post/PostListResponseDto.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FEAT

#55 [FIX] 여행지 조회 API 조건 추가 및 검색 추가
  src/main/java/com/jida/controller/AttractionController.java
  src/main/resources/mapper/attraction.xml
Labels: JIHUN, FIX

#56 [FIX] 로그인 API 수정
  pom.xml
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/domain/Authority.java
  src/main/java/com/jida/domain/Member.java
  src/main/java/com/jida/dto/req/MemberSaveRequestDto.java
  src/main/java/com/jida/dto/res/member/TokenDto.java
  src/main/java/com/jida/dto/res/member/TokenResponse.java
  src/main/java/com/jida/jwt/JWTUtil.java
  src/main/java/com/jida/jwt/JwtFilter.java
  src/main/java/com/jida/jwt/LoginFilter.java
  src/main/java/com/jida/mapper/MemberMapper.java
  src/main/java/com/jida/security/SecurityConfig.java
  src/main/java/com/jida/service/CustomUserDetails.java
  src/main/java/com/jida/service/CustomUserDetailsService.java
  src/main/java/com/jida/service/MemberService.java
  src/main/java/com/jida/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/member.xml
Labels: DAIN, FIX

#58 [FIX] 여행지 조회 시 type 여러개 받도록 수정
  src/main/java/com/jida/controller/AttractionController.java
  src/main/resources/mapper/attraction.xml
Labels: JIHUN, FIX

#60 [FIX] 게시글 갯수 계산 쿼리문 오류 수정
  src/main/resources/mapper/post.xml
Labels: JIHUN, FIX

#62 [FIX] CORS에러, 회원가입, 로그인 api url 수정
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/jwt/LoginFilter.java
  src/main/java/com/jida/security/SecurityConfig.java
Labels: DAIN, FIX

#64 [FEAT] 로그인, 토큰재발급, 로그아웃 API 추가
  pom.xml
  src/main/java/com/jida/config/WebConfiguration.java
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/domain/Member.java
  src/main/java/com/jida/dto/req/MemberSaveRequestDto.java
  src/main/java/com/jida/dto/res/member/MemberDetailResponseDto.java
  src/main/java/com/jida/exception/UnAuthorizedException.java
  src/main/java/com/jida/interceptor/JWTInterceptor.java
  src/main/java/com/jida/jwt/JWTUtil.java
  src/main/java/com/jida/jwt/JwtFilter.java
  src/main/java/com/jida/jwt/LoginFilter.java
  src/main/java/com/jida/mapper/MemberMapper.java
  src/main/java/com/jida/security/SecurityConfig.java
  src/main/java/com/jida/service/CustomUserDetails.java
  src/main/java/com/jida/service/CustomUserDetailsService.java
  src/main/java/com/jida/service/MemberService.java
  src/main/java/com/jida/service/MemberServiceImpl.java
  src/main/java/com/jida/util/JWTUtil.java
  src/main/resources/application.properties
  src/main/resources/mapper/member.xml
Labels: DAIN, FEAT

#66 [FIX] 게시글 저장 API 수정
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/domain/Member.java
  src/main/java/com/jida/dto/res/member/MemberDetailResponseDto.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
Labels: DAIN, FEAT, FIX

#69 [FIX] 여행지 조회 정렬 쿼리 수정
  src/main/resources/mapper/attraction.xml
Labels: JIHUN, FIX

#72 [FEAT] 쪽지룸 목록 조회 API 구현
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/MessageController.java
  src/main/java/com/jida/domain/Message.java
  src/main/java/com/jida/domain/MessageRoom.java
  src/main/java/com/jida/dto/res/message/MessageRoomResponse.java
  src/main/java/com/jida/dto/res/message/MessageRoomResponseDto.java
  src/main/java/com/jida/mapper/MessageMapper.java
  src/main/java/com/jida/mapper/MessageRoomMapper.java
  src/main/java/com/jida/service/MessageService.java
  src/main/java/com/jida/service/MessageServiceImpl.java
  src/main/resources/mapper/message.xml
  src/main/resources/mapper/messageRoom.xml
Labels: DAIN, FEAT

#74 [FEAT] 쪽지전송, 답장시 에러 구현
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/service/MessageServiceImpl.java
Labels: DAIN, FEAT

#76 [FEAT] 쪽지 목록 조회 API 구현
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/MessageController.java
  src/main/java/com/jida/dto/res/message/MessageDetailResponse.java
  src/main/java/com/jida/dto/res/message/MessageDetailResponseDto.java
  src/main/java/com/jida/mapper/MessageMapper.java
  src/main/java/com/jida/service/MessageService.java
  src/main/java/com/jida/service/MessageServiceImpl.java
  src/main/resources/mapper/message.xml
Labels: DAIN, FEAT

#79 [FIX, FEAT] 유저정보 수정, 게시글 업데이트 수정, 댓글 전체조회 수정
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/controller/CommentController.java
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/domain/Post.java
  src/main/java/com/jida/service/CommentService.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/comment.xml
  src/main/resources/mapper/post.xml
Labels: DAIN, FEAT, FIX

#81 [FEAT] 토큰에 memberId(PK) 저장
  src/main/java/com/jida/util/JWTUtil.java
Labels: DAIN, FEAT

#82 [FEAT] 나의 여행계획 생성 API 구현
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PlanController.java
  src/main/java/com/jida/domain/Attraction.java
  src/main/java/com/jida/domain/Plan.java
  src/main/java/com/jida/domain/PlanList.java
  src/main/java/com/jida/dto/req/PlanSaveRequestDto.java
  src/main/java/com/jida/dto/res/plan/PlanListResponse.java
  src/main/java/com/jida/dto/res/plan/PlanListResponseDto.java
  src/main/java/com/jida/dto/res/plan/PlanResponse.java
  src/main/java/com/jida/mapper/AttractionMapper.java
  src/main/java/com/jida/mapper/PlanListMapper.java
  src/main/java/com/jida/mapper/PlanMapper.java
  src/main/java/com/jida/service/AttractionService.java
  src/main/java/com/jida/service/AttractionServiceImpl.java
  src/main/java/com/jida/service/PlanListService.java
  src/main/java/com/jida/service/PlanListServiceImpl.java
  src/main/java/com/jida/service/PlanService.java
  src/main/java/com/jida/service/PlanServiceImpl.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/attraction.xml
  src/main/resources/mapper/plan.xml
  src/main/resources/mapper/planList.xml
Labels: JIHUN, FEAT

#83 [FEAT] 계획 저장 시 여행지 계획 개수 추가 API 구현
  src/main/java/com/jida/dto/res/attraction/AttractionListResponseDto.java
  src/main/java/com/jida/mapper/AttractionMapper.java
  src/main/java/com/jida/service/AttractionService.java
  src/main/java/com/jida/service/AttractionServiceImpl.java
  src/main/java/com/jida/service/PlanServiceImpl.java
  src/main/resources/mapper/attraction.xml
Labels: JIHUN, FEAT

#88 [FEAT] 나의 여행계획 수정 API 구현
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PlanController.java
  src/main/java/com/jida/domain/Plan.java
  src/main/java/com/jida/dto/req/PlanSaveRequestDto.java
  src/main/java/com/jida/dto/req/PlanUpdateRequestDto.java
  src/main/java/com/jida/mapper/PlanMapper.java
  src/main/java/com/jida/service/PlanService.java
  src/main/java/com/jida/service/PlanServiceImpl.java
  src/main/resources/mapper/plan.xml
Labels: JIHUN, FEAT

#90 [FEAT] 나의 여행 계획 삭제 API 구현
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PlanListController.java
  src/main/java/com/jida/mapper/PlanListMapper.java
  src/main/java/com/jida/service/PlanListService.java
  src/main/java/com/jida/service/PlanListServiceImpl.java
  src/main/resources/mapper/planList.xml
Labels: JIHUN, FEAT

#93 [FIX] 여행 계획 저장, 조회, 수정 시 title 추가
  src/main/java/com/jida/domain/PlanList.java
  src/main/java/com/jida/dto/req/PlanListSaveRequestDto.java
  src/main/java/com/jida/dto/req/PlanSaveRequestDto.java
  src/main/java/com/jida/dto/res/plan/PlanListResponseDto.java
  src/main/java/com/jida/mapper/PlanListMapper.java
  src/main/java/com/jida/service/PlanListService.java
  src/main/java/com/jida/service/PlanListServiceImpl.java
  src/main/java/com/jida/service/PlanServiceImpl.java
  src/main/resources/mapper/plan.xml
  src/main/resources/mapper/planList.xml
Labels: JIHUN, FIX

#94 [FEAT] 나의 모든 여행계획 조회 API 구현
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PlanListController.java
  src/main/java/com/jida/domain/PlanList.java
  src/main/java/com/jida/dto/res/plan/PlanAllListResponse.java
  src/main/java/com/jida/dto/res/plan/PlanAllListResponseDto.java
  src/main/java/com/jida/mapper/PlanListMapper.java
  src/main/java/com/jida/service/PlanListService.java
  src/main/java/com/jida/service/PlanListServiceImpl.java
  src/main/resources/mapper/planList.xml
Labels: JIHUN, FEAT

#95 [FEAT] 내가 쓴 글 조회 기능 구현
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: DAIN, FEAT

#97 [FIX] 여행계획 날짜 null처리
  src/main/java/com/jida/dto/res/plan/PlanListResponseDto.java
Labels: JIHUN, FIX

#99 [FEAT] 내 정보 수정 api 기능 구현
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/mapper/MemberMapper.java
  src/main/java/com/jida/service/MemberService.java
  src/main/java/com/jida/service/MemberServiceImpl.java
  src/main/resources/mapper/member.xml
Labels: DAIN, FEAT

#101 [FIX] 내가 쓴 글 조회시 member,board null 값 join 수정
  src/main/resources/mapper/post.xml
Labels: DAIN, FIX

#103 [FIX] 계획 전체 조회 시 빈 이미지 처리
  src/main/resources/mapper/planList.xml
Labels: JIHUN, FIX

#105 [FEAT] 여행일정 공유여부 저장 API 구현
  src/main/java/com/jida/constants/ExceptionCode.java
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/PlanController.java
  src/main/java/com/jida/domain/Plan.java
  src/main/java/com/jida/dto/req/PlanSaveRequestDto.java
  src/main/java/com/jida/dto/res/plan/PlanListResponseDto.java
  src/main/java/com/jida/mapper/PlanMapper.java
  src/main/java/com/jida/service/PlanService.java
  src/main/java/com/jida/service/PlanServiceImpl.java
  src/main/resources/mapper/plan.xml
Labels: JIHUN, FEAT

#106 [FEAT] 여행 추천친구 조회 API 구현
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/controller/PlanController.java
  src/main/java/com/jida/dto/res/plan/PlanMemberResponse.java
  src/main/java/com/jida/dto/res/plan/PlanMemberResponseDto.java
  src/main/java/com/jida/mapper/MemberMapper.java
  src/main/java/com/jida/mapper/PlanMapper.java
  src/main/java/com/jida/service/MemberService.java
  src/main/java/com/jida/service/MemberServiceImpl.java
  src/main/java/com/jida/service/PlanService.java
  src/main/java/com/jida/service/PlanServiceImpl.java
  src/main/resources/mapper/member.xml
Labels: DAIN, FEAT

#108 [FIX] 여행계획저장 API 반환값 수정
  src/main/java/com/jida/controller/PlanController.java
  src/main/java/com/jida/service/PlanService.java
  src/main/java/com/jida/service/PlanServiceImpl.java
Labels: JIHUN, FIX

#111 [FIX] 댓글 조회 순서 및 반환값 변경
  src/main/java/com/jida/controller/CommentController.java
  src/main/java/com/jida/dto/req/CommentSaveRequestDto.java
  src/main/java/com/jida/dto/res/comment/CommentListResponseDto.java
  src/main/java/com/jida/service/CommentService.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/resources/mapper/comment.xml
Labels: JIHUN, FIX

#113 [FEAT] 내가 단 댓글 조회 API 구현
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/mapper/CommentMapper.java
  src/main/java/com/jida/service/CommentService.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/resources/mapper/comment.xml
Labels: DAIN, FEAT

#115 [FEAT] 여행지 이미지 인기순 조회 API
  src/main/java/com/jida/controller/AttractionController.java
  src/main/java/com/jida/mapper/AttractionMapper.java
  src/main/java/com/jida/service/AttractionService.java
  src/main/java/com/jida/service/AttractionServiceImpl.java
  src/main/resources/mapper/attraction.xml
Labels: DAIN, FEAT

#117 [FIX] 댓글 저장 API 반환값 수정
  src/main/java/com/jida/controller/CommentController.java
  src/main/java/com/jida/dto/res/comment/CommentDetailResponseDto.java
  src/main/java/com/jida/service/CommentService.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/resources/mapper/comment.xml
Labels: JIHUN, FIX

#119 [FIX] 댓글 삭제시 갯수 감소 로직 변경
  src/main/java/com/jida/dto/res/comment/CommentDetailResponseDto.java
  src/main/java/com/jida/mapper/PostMapper.java
  src/main/java/com/jida/service/CommentServiceImpl.java
  src/main/resources/mapper/post.xml
Labels: JIHUN, FIX

#121 [FIX] 게시글 상세조회 반환값에 좋아요, 스크랩 여부 추가
  src/main/java/com/jida/controller/PostController.java
  src/main/java/com/jida/dto/res/post/PostDetailResponseDto.java
  src/main/java/com/jida/mapper/PostLikeMapper.java
  src/main/java/com/jida/mapper/PostScrapMapper.java
  src/main/java/com/jida/service/PostService.java
  src/main/java/com/jida/service/PostServiceImpl.java
  src/main/resources/mapper/postLike.xml
  src/main/resources/mapper/postScrap.xml
Labels: JIHUN, FIX

#123 [FEAT] 회원탈퇴 API
  src/main/java/com/jida/constants/SuccessCode.java
  src/main/java/com/jida/controller/MemberController.java
  src/main/java/com/jida/mapper/MemberMapper.java
  src/main/java/com/jida/service/MemberService.java
  src/main/java/com/jida/service/MemberServiceImpl.java
  src/main/resources/mapper/member.xml
Labels: DAIN, FEAT

#127 [FEAT] 쪽지보낼 때 여행 공유 가능하게 API 수정
  src/main/java/com/jida/controller/MessageController.java
  src/main/java/com/jida/domain/Message.java
  src/main/java/com/jida/dto/req/MessageRequestDto.java
  src/main/java/com/jida/dto/res/message/MessageDetailResponseDto.java
  src/main/java/com/jida/dto/res/message/MessageSendResponseDto.java
  src/main/java/com/jida/service/MessageServiceImpl.java
  src/main/java/com/jida/service/PlanServiceImpl.java
  src/main/resources/mapper/message.xml
Labels: JIHUN, FEAT
